/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for RedirectFallbackMethodEnum
 */
export enum RedirectFallbackMethodEnum {
  POST = 'POST',
  GET = 'GET',
}

/**
 * Schema for RedirectFallbackMethodEnum
 */
export const redirectFallbackMethodEnumSchema: Schema<RedirectFallbackMethodEnum> = stringEnum(RedirectFallbackMethodEnum);
