/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for State2Enum
 */
export enum State2Enum {
  NOTRECORDING = 'NOT_RECORDING',
  PAUSED = 'PAUSED',
  RECORDING = 'RECORDING',
}

/**
 * Schema for State2Enum
 */
export const state2EnumSchema: Schema<State2Enum> = stringEnum(State2Enum);
