/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Status3Enum
 */
export enum Status3Enum {
  None = 'none',
  Processing = 'processing',
  Available = 'available',
  Error = 'error',
  Timeout = 'timeout',
  Filesizetoobig = 'file-size-too-big',
  Filesizetoosmall = 'file-size-too-small',
}

/**
 * Schema for Status3Enum
 */
export const status3EnumSchema: Schema<Status3Enum> = stringEnum(Status3Enum);
