/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Status1Enum
 */
export enum Status1Enum {
  Processing = 'processing',
  Partial = 'partial',
  Complete = 'complete',
  Deleted = 'deleted',
  Error = 'error',
  Alreadyinprogress = 'already-in-progress',
}

/**
 * Schema for Status1Enum
 */
export const status1EnumSchema: Schema<Status1Enum> = stringEnum(Status1Enum);
