/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import { Status3Enum, status3EnumSchema } from './status3Enum';

export interface Transcription {
  id?: string;
  status?: Status3Enum;
  completedTime?: string;
  url?: string;
}

export const transcriptionSchema: Schema<Transcription> = object({
  id: ['id', optional(string())],
  status: ['status', optional(status3EnumSchema)],
  completedTime: ['completedTime', optional(string())],
  url: ['url', optional(string())],
});
