/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of Api
 */
interface Api {
  type?: string;
  description?: string;
  id?: string | null;
}

export class ExternalApiError extends ApiError<Api> {}
