apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  schemaVersion: v1.0.0
  name: node-voice-location
  description: Links to additional entities in the node-voice repository.
  annotations:
    github.com/project-slug: Bandwidth/node-voice
spec:
  targets:
    - ./component.yaml
