/**
 * VoiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of ApiCallResponse
 */
class ApiCallResponse extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.accountId = this.constructor.getValue(obj.accountId);
        this.callId = this.constructor.getValue(obj.callId);
        this.applicationId = this.constructor.getValue(obj.applicationId);
        this.to = this.constructor.getValue(obj.to);
        this.from = this.constructor.getValue(obj.from);
        this.startTime = this.constructor.getValue(obj.startTime);
        this.callUrl = this.constructor.getValue(obj.callUrl);
        this.callTimeout = this.constructor.getValue(obj.callTimeout);
        this.callbackTimeout = this.constructor.getValue(obj.callbackTimeout);
        this.answerUrl = this.constructor.getValue(obj.answerUrl);
        this.answerMethod = this.constructor.getValue(obj.answerMethod);
        this.answerFallbackUrl = this.constructor.getValue(obj.answerFallbackUrl);
        this.answerFallbackMethod = this.constructor.getValue(obj.answerFallbackMethod);
        this.disconnectUrl = this.constructor.getValue(obj.disconnectUrl);
        this.disconnectMethod = this.constructor.getValue(obj.disconnectMethod);
        this.username = this.constructor.getValue(obj.username);
        this.password = this.constructor.getValue(obj.password);
        this.fallbackUsername = this.constructor.getValue(obj.fallbackUsername);
        this.fallbackPassword = this.constructor.getValue(obj.fallbackPassword);
        this.tag = this.constructor.getValue(obj.tag);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'accountId', realName: 'accountId' },
            { name: 'callId', realName: 'callId' },
            { name: 'applicationId', realName: 'applicationId' },
            { name: 'to', realName: 'to' },
            { name: 'from', realName: 'from' },
            {
                name: 'startTime',
                realName: 'startTime',
                isDateTime: true,
                dateTimeValue: 'rfc3339',
            },
            { name: 'callUrl', realName: 'callUrl' },
            { name: 'callTimeout', realName: 'callTimeout' },
            { name: 'callbackTimeout', realName: 'callbackTimeout' },
            { name: 'answerUrl', realName: 'answerUrl' },
            { name: 'answerMethod', realName: 'answerMethod' },
            { name: 'answerFallbackUrl', realName: 'answerFallbackUrl' },
            { name: 'answerFallbackMethod', realName: 'answerFallbackMethod' },
            { name: 'disconnectUrl', realName: 'disconnectUrl' },
            { name: 'disconnectMethod', realName: 'disconnectMethod' },
            { name: 'username', realName: 'username' },
            { name: 'password', realName: 'password' },
            { name: 'fallbackUsername', realName: 'fallbackUsername' },
            { name: 'fallbackPassword', realName: 'fallbackPassword' },
            { name: 'tag', realName: 'tag' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = ApiCallResponse;
