/**
 * VoiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of ApiCallStateResponse
 */
class ApiCallStateResponse extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.callId = this.constructor.getValue(obj.callId);
        this.parentCallId = this.constructor.getValue(obj.parentCallId);
        this.applicationId = this.constructor.getValue(obj.applicationId);
        this.accountId = this.constructor.getValue(obj.accountId);
        this.to = this.constructor.getValue(obj.to);
        this.from = this.constructor.getValue(obj.from);
        this.direction = this.constructor.getValue(obj.direction);
        this.state = this.constructor.getValue(obj.state);
        this.startTime = this.constructor.getValue(obj.startTime);
        this.answerTime = this.constructor.getValue(obj.answerTime);
        this.endTime = this.constructor.getValue(obj.endTime);
        this.disconnectCause = this.constructor.getValue(obj.disconnectCause);
        this.errorMessage = this.constructor.getValue(obj.errorMessage);
        this.errorId = this.constructor.getValue(obj.errorId);
        this.lastUpdate = this.constructor.getValue(obj.lastUpdate);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'callId', realName: 'callId' },
            { name: 'parentCallId', realName: 'parentCallId' },
            { name: 'applicationId', realName: 'applicationId' },
            { name: 'accountId', realName: 'accountId' },
            { name: 'to', realName: 'to' },
            { name: 'from', realName: 'from' },
            { name: 'direction', realName: 'direction' },
            { name: 'state', realName: 'state' },
            {
                name: 'startTime',
                realName: 'startTime',
                isDateTime: true,
                dateTimeValue: 'rfc3339',
            },
            {
                name: 'answerTime',
                realName: 'answerTime',
                isDateTime: true,
                dateTimeValue: 'rfc3339',
            },
            { name: 'endTime', realName: 'endTime', isDateTime: true, dateTimeValue: 'rfc3339' },
            { name: 'disconnectCause', realName: 'disconnectCause' },
            { name: 'errorMessage', realName: 'errorMessage' },
            { name: 'errorId', realName: 'errorId' },
            {
                name: 'lastUpdate',
                realName: 'lastUpdate',
                isDateTime: true,
                dateTimeValue: 'rfc3339',
            },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = ApiCallStateResponse;
