/**
 * VoiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of ApiGetAccountRecordingsMetadataRequest
 */
class ApiGetAccountRecordingsMetadataRequest extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.from = this.constructor.getValue(obj.from);
        this.to = this.constructor.getValue(obj.to);
        this.minStartTime = this.constructor.getValue(obj.minStartTime);
        this.maxStartTime = this.constructor.getValue(obj.maxStartTime);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'from', realName: 'from' },
            { name: 'to', realName: 'to' },
            {
                name: 'minStartTime',
                realName: 'minStartTime',
                isDateTime: true,
                dateTimeValue: 'rfc3339',
            },
            {
                name: 'maxStartTime',
                realName: 'maxStartTime',
                isDateTime: true,
                dateTimeValue: 'rfc3339',
            },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = ApiGetAccountRecordingsMetadataRequest;
