/**
 * VoiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of CallEngineModifyConferenceRequest
 */
class CallEngineModifyConferenceRequest extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.status = this.constructor.getValue(obj.status);
        this.redirectUrl = this.constructor.getValue(obj.redirectUrl);
        this.redirectFallbackUrl = this.constructor.getValue(obj.redirectFallbackUrl);
        this.redirectMethod = this.constructor.getValue(obj.redirectMethod);
        this.redirectFallbackMethod = this.constructor.getValue(obj.redirectFallbackMethod);
        this.username = this.constructor.getValue(obj.username);
        this.password = this.constructor.getValue(obj.password);
        this.fallbackUsername = this.constructor.getValue(obj.fallbackUsername);
        this.fallbackPassword = this.constructor.getValue(obj.fallbackPassword);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'status', realName: 'status' },
            { name: 'redirectUrl', realName: 'redirectUrl' },
            { name: 'redirectFallbackUrl', realName: 'redirectFallbackUrl' },
            { name: 'redirectMethod', realName: 'redirectMethod' },
            { name: 'redirectFallbackMethod', realName: 'redirectFallbackMethod' },
            { name: 'username', realName: 'username' },
            { name: 'password', realName: 'password' },
            { name: 'fallbackUsername', realName: 'fallbackUsername' },
            { name: 'fallbackPassword', realName: 'fallbackPassword' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = CallEngineModifyConferenceRequest;
