/**
 * VoiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of ConferenceDetail
 */
class ConferenceDetail extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.id = this.constructor.getValue(obj.id);
        this.name = this.constructor.getValue(obj.name);
        this.createdTime = this.constructor.getValue(obj.createdTime);
        this.completedTime = this.constructor.getValue(obj.completedTime);
        this.conferenceEventUrl = this.constructor.getValue(obj.conferenceEventUrl);
        this.conferenceEventMethod = this.constructor.getValue(obj.conferenceEventMethod);
        this.tag = this.constructor.getValue(obj.tag);
        this.activeMembers = this.constructor.getValue(obj.activeMembers);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'id', realName: 'id' },
            { name: 'name', realName: 'name' },
            {
                name: 'createdTime',
                realName: 'createdTime',
                isDateTime: true,
                dateTimeValue: 'rfc3339',
            },
            {
                name: 'completedTime',
                realName: 'completedTime',
                isDateTime: true,
                dateTimeValue: 'rfc3339',
            },
            { name: 'conferenceEventUrl', realName: 'conferenceEventUrl' },
            { name: 'conferenceEventMethod', realName: 'conferenceEventMethod' },
            { name: 'tag', realName: 'tag' },
            {
                name: 'activeMembers',
                realName: 'activeMembers',
                array: true,
                type: 'ConferenceMemberDetail',
            },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = ConferenceDetail;
