/**
 * VoiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const ConferenceEventMethodEnum = {

    /**
     * TODO: Write general description for this element
     */
    GET: 'GET',

    /**
     * TODO: Write general description for this element
     */
    HEAD: 'HEAD',

    /**
     * TODO: Write general description for this element
     */
    POST: 'POST',

    /**
     * TODO: Write general description for this element
     */
    PUT: 'PUT',

    /**
     * TODO: Write general description for this element
     */
    PATCH: 'PATCH',

    /**
     * TODO: Write general description for this element
     */
    MDELETE: 'DELETE',

    /**
     * TODO: Write general description for this element
     */
    OPTIONS: 'OPTIONS',

    /**
     * TODO: Write general description for this element
     */
    TRACE: 'TRACE',

};

module.exports = ConferenceEventMethodEnum;
