/**
 * VoiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const DirectionEnum = {

    /**
     * TODO: Write general description for this element
     */
    INBOUND: 'inbound',

    /**
     * TODO: Write general description for this element
     */
    OUTBOUND: 'outbound',

};

module.exports = DirectionEnum;
