/**
 * VoiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const DisconnectCauseEnum = {

    /**
     * TODO: Write general description for this element
     */
    BUSY: 'busy',

    /**
     * TODO: Write general description for this element
     */
    CALLBACKERROR: 'callback-error',

    /**
     * TODO: Write general description for this element
     */
    CANCEL: 'cancel',

    /**
     * TODO: Write general description for this element
     */
    ERROR: 'error',

    /**
     * TODO: Write general description for this element
     */
    HANGUP: 'hangup',

    /**
     * TODO: Write general description for this element
     */
    INVALIDBXML: 'invalid-bxml',

    /**
     * TODO: Write general description for this element
     */
    REJECTED: 'rejected',

    /**
     * TODO: Write general description for this element
     */
    TIMEOUT: 'timeout',

    /**
     * TODO: Write general description for this element
     */
    ACCOUNTLIMIT: 'account-limit',

    /**
     * TODO: Write general description for this element
     */
    NODECAPACITYEXCEEDED: 'node-capacity-exceeded',

    /**
     * TODO: Write general description for this element
     */
    UNKNOWN: 'unknown',

    /**
     * TODO: Write general description for this element
     */
    APPLICATIONERROR: 'application-error',

};

module.exports = DisconnectCauseEnum;
