/**
 * VoiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const FileFormatEnum = {

    /**
     * TODO: Write general description for this element
     */
    MP_3: 'mp3',

    /**
     * TODO: Write general description for this element
     */
    WAV: 'wav',

};

module.exports = FileFormatEnum;
