/**
 * VoiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of RecordingMetadataResponse
 */
class RecordingMetadataResponse extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.accountId = this.constructor.getValue(obj.accountId);
        this.callId = this.constructor.getValue(obj.callId);
        this.recordingId = this.constructor.getValue(obj.recordingId);
        this.to = this.constructor.getValue(obj.to);
        this.from = this.constructor.getValue(obj.from);
        this.duration = this.constructor.getValue(obj.duration);
        this.direction = this.constructor.getValue(obj.direction);
        this.channels = this.constructor.getValue(obj.channels);
        this.startTime = this.constructor.getValue(obj.startTime);
        this.endTime = this.constructor.getValue(obj.endTime);
        this.fileFormat = this.constructor.getValue(obj.fileFormat);
        this.transcriptionStatus = this.constructor.getValue(obj.transcriptionStatus);
        this.mediaUrl = this.constructor.getValue(obj.mediaUrl);
        this.transcriptionUrl = this.constructor.getValue(obj.transcriptionUrl);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'accountId', realName: 'accountId' },
            { name: 'callId', realName: 'callId' },
            { name: 'recordingId', realName: 'recordingId' },
            { name: 'to', realName: 'to' },
            { name: 'from', realName: 'from' },
            { name: 'duration', realName: 'duration' },
            { name: 'direction', realName: 'direction' },
            { name: 'channels', realName: 'channels' },
            { name: 'startTime', realName: 'startTime' },
            { name: 'endTime', realName: 'endTime' },
            { name: 'fileFormat', realName: 'fileFormat' },
            { name: 'transcriptionStatus', realName: 'transcriptionStatus' },
            { name: 'mediaUrl', realName: 'mediaUrl' },
            { name: 'transcriptionUrl', realName: 'transcriptionUrl' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = RecordingMetadataResponse;
