/**
 * VoiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const RedirectMethodEnum = {

    /**
     * TODO: Write general description for this element
     */
    POST: 'POST',

    /**
     * TODO: Write general description for this element
     */
    GET: 'GET',

};

module.exports = RedirectMethodEnum;
