/**
 * VoiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const StatusEnum = {

    /**
     * TODO: Write general description for this element
     */
    ACTIVE: 'active',

    /**
     * TODO: Write general description for this element
     */
    COMPLETED: 'completed',

};

module.exports = StatusEnum;
