/**
 * VoiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const StateEnum = {

    /**
     * TODO: Write general description for this element
     */
    DISCONNECTED: 'DISCONNECTED',

    /**
     * TODO: Write general description for this element
     */
    ANSWERED: 'ANSWERED',

    /**
     * TODO: Write general description for this element
     */
    INITIATED: 'INITIATED',

};

module.exports = StateEnum;
