/**
 * VoiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const State1Enum = {

    /**
     * TODO: Write general description for this element
     */
    NOT_RECORDING: 'NOT_RECORDING',

    /**
     * TODO: Write general description for this element
     */
    PAUSED: 'PAUSED',

    /**
     * TODO: Write general description for this element
     */
    RECORDING: 'RECORDING',

};

module.exports = State1Enum;
