/**
 * VoiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const StatusEnum = {

    /**
     * TODO: Write general description for this element
     */
    PROCESSING: 'processing',

    /**
     * TODO: Write general description for this element
     */
    PARTIAL: 'partial',

    /**
     * TODO: Write general description for this element
     */
    COMPLETE: 'complete',

    /**
     * TODO: Write general description for this element
     */
    DELETED: 'deleted',

    /**
     * TODO: Write general description for this element
     */
    ERROR: 'error',

};

module.exports = StatusEnum;
