/**
 * VoiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const Status1Enum = {

    /**
     * TODO: Write general description for this element
     */
    REQUESTED: 'requested',

    /**
     * TODO: Write general description for this element
     */
    NONE: 'none',

    /**
     * TODO: Write general description for this element
     */
    PROCESSING: 'processing',

    /**
     * TODO: Write general description for this element
     */
    AVAILABLE: 'available',

    /**
     * TODO: Write general description for this element
     */
    ERROR: 'error',

    /**
     * TODO: Write general description for this element
     */
    TIMEOUT: 'timeout',

    /**
     * TODO: Write general description for this element
     */
    FILESIZETOOBIG: 'file-size-too-big',

};

module.exports = Status1Enum;
