/**
 * VoiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const Status3Enum = {

    /**
     * TODO: Write general description for this element
     */
    NONE: 'none',

    /**
     * TODO: Write general description for this element
     */
    PROCESSING: 'processing',

    /**
     * TODO: Write general description for this element
     */
    AVAILABLE: 'available',

    /**
     * TODO: Write general description for this element
     */
    ERROR: 'error',

    /**
     * TODO: Write general description for this element
     */
    TIMEOUT: 'timeout',

    /**
     * TODO: Write general description for this element
     */
    FILESIZETOOBIG: 'file-size-too-big',

    /**
     * TODO: Write general description for this element
     */
    FILESIZETOOSMALL: 'file-size-too-small',

};

module.exports = Status3Enum;
