/**
 * VoiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const TranscriptionStatusEnum = {

    /**
     * TODO: Write general description for this element
     */
    NONE: 'none',

    /**
     * TODO: Write general description for this element
     */
    REQUESTED: 'requested',

    /**
     * TODO: Write general description for this element
     */
    AVAILABLE: 'available',

};

module.exports = TranscriptionStatusEnum;
