/**
 * VoiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const TypeEnum = {

    /**
     * TODO: Write general description for this element
     */
    VALIDATION: 'validation',

    /**
     * TODO: Write general description for this element
     */
    AUTHENTICATIONERROR: 'authentication-error',

    /**
     * TODO: Write general description for this element
     */
    AUTHORIZATIONERROR: 'authorization-error',

    /**
     * TODO: Write general description for this element
     */
    INTERNALERROR: 'internal-error',

    /**
     * TODO: Write general description for this element
     */
    ERROR: 'error',

    /**
     * TODO: Write general description for this element
     */
    RATELIMITEXCEEDED: 'rate-limit-exceeded',

    /**
     * TODO: Write general description for this element
     */
    SYSTEMOVERLOADED: 'system-overloaded',

};

module.exports = TypeEnum;
