/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { ApiError } from './apiError';

/**
 * Creates an instance of ApiErrorResponseError
 */
interface ApiErrorResponseError {
  type?: string;
  description?: string;
  id?: string;
}

export class ApiErrorResponseErrorError extends ApiError<ApiErrorResponseError> {}
