/**
 * VoiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const ApiCallResponse = require('../lib/Models/ApiCallResponse');
const ApiCallStateResponse = require('../lib/Models/ApiCallStateResponse');
const ApiCreateCallRequest = require('../lib/Models/ApiCreateCallRequest');
const ApiModifyCallRequest = require('../lib/Models/ApiModifyCallRequest');
const ApiTranscribeRecordingRequest = require('../lib/Models/ApiTranscribeRecordingRequest');
const CallEngineModifyConferenceRequest =
  require('../lib/Models/CallEngineModifyConferenceRequest');
const ModifyCallRecordingState = require('../lib/Models/ModifyCallRecordingState');
const RecordingMetadataResponse = require('../lib/Models/RecordingMetadataResponse');
const Transcript = require('../lib/Models/Transcript');
const Transcription = require('../lib/Models/Transcription');
const TranscriptionResponse = require('../lib/Models/TranscriptionResponse');
const ApiErrorResponseException = require('../lib/Exceptions/ApiErrorResponseException');

const classMap = {
    ApiCallResponse,
    ApiCallStateResponse,
    ApiCreateCallRequest,
    ApiModifyCallRequest,
    ApiTranscribeRecordingRequest,
    CallEngineModifyConferenceRequest,
    ModifyCallRecordingState,
    RecordingMetadataResponse,
    Transcript,
    Transcription,
    TranscriptionResponse,
    ApiErrorResponseException,
};

/**
 * Factory class to create instances of models and exception classes
 */
class ModelFactory {
    /**
     * Creates instance of a model class
     * @param  modelName  {string}  Name of class to instantiate
     * @returns  {object} Instance of the model class
     */
    static getInstance(modelName) {
        return new classMap[modelName]();
    }
}

module.exports = ModelFactory;
