/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for AnswerMethodEnum
 */
export enum AnswerMethodEnum {
  POST = 'POST',
  GET = 'GET',
}

/**
 * Schema for AnswerMethodEnum
 */
export const answerMethodEnumSchema: Schema<AnswerMethodEnum> = stringEnum(AnswerMethodEnum);
