/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';
import {
  CallbackMethodEnum,
  callbackMethodEnumSchema,
} from './callbackMethodEnum';

export interface ApiTranscribeRecordingRequest {
  callbackUrl?: string;
  callbackMethod?: CallbackMethodEnum;
  username?: string;
  password?: string;
  tag?: string;
  callbackTimeout?: number;
}

export const apiTranscribeRecordingRequestSchema: Schema<ApiTranscribeRecordingRequest> = object(
  {
    callbackUrl: ['callbackUrl', optional(string())],
    callbackMethod: ['callbackMethod', optional(callbackMethodEnumSchema)],
    username: ['username', optional(string())],
    password: ['password', optional(string())],
    tag: ['tag', optional(string())],
    callbackTimeout: ['callbackTimeout', optional(number())],
  }
);
