/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for CallbackMethodEnum
 */
export enum CallbackMethodEnum {
  GET = 'GET',
  HEAD = 'HEAD',
  POST = 'POST',
  PUT = 'PUT',
  PATCH = 'PATCH',
  DELETE = 'DELETE',
  OPTIONS = 'OPTIONS',
  TRACE = 'TRACE',
}

/**
 * Schema for CallbackMethodEnum
 */
export const callbackMethodEnumSchema: Schema<CallbackMethodEnum> = stringEnum(CallbackMethodEnum);
