/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  dictWithXmlEntries,
  nullable,
  object,
  optional,
  Schema,
  string,
} from '../schema';

export interface CallState {
  callId?: string;
  parentCallId?: string | null;
  applicationId?: string;
  accountId?: string;
  to?: string;
  from?: string;
  direction?: string;
  /** The current state of the call. Current possible values are 'initiated', 'answered' and 'disconnected'. Additional states may be added in the future, so your application must be tolerant of unknown values. */
  state?: string;
  identity?: string | null;
  stirShaken?: Record<string, string>;
  startTime?: string;
  answerTime?: string | null;
  endTime?: string | null;
  /** The reason the call was disconnected, or null if the call is still active. Current values are 'cancel', 'timeout', 'busy', 'rejected', 'hangup', 'invalid-bxml', 'callback-error', 'application-error', 'error', 'account-limit', 'node-capacity-exceeded' and 'unknown'. Additional causes may be added in the future, so your application must be tolerant of unknown values. */
  disconnectCause?: string | null;
  errorMessage?: string | null;
  errorId?: string | null;
  lastUpdate?: string;
}

export const callStateSchema: Schema<CallState> = object({
  callId: ['callId', optional(string())],
  parentCallId: ['parentCallId', optional(nullable(string()))],
  applicationId: ['applicationId', optional(string())],
  accountId: ['accountId', optional(string())],
  to: ['to', optional(string())],
  from: ['from', optional(string())],
  direction: ['direction', optional(string())],
  state: ['state', optional(string())],
  identity: ['identity', optional(nullable(string()))],
  stirShaken: ['stirShaken', optional(dictWithXmlEntries(string()))],
  startTime: ['startTime', optional(string())],
  answerTime: ['answerTime', optional(nullable(string()))],
  endTime: ['endTime', optional(nullable(string()))],
  disconnectCause: ['disconnectCause', optional(nullable(string()))],
  errorMessage: ['errorMessage', optional(nullable(string()))],
  errorId: ['errorId', optional(nullable(string()))],
  lastUpdate: ['lastUpdate', optional(string())],
});
