/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import {
  RedirectFallbackMethodEnum,
  redirectFallbackMethodEnumSchema,
} from './redirectFallbackMethodEnum';
import {
  RedirectMethodEnum,
  redirectMethodEnumSchema,
} from './redirectMethodEnum';
import { StatusEnum, statusEnumSchema } from './statusEnum';

export interface CallEngineModifyConferenceRequest {
  status?: StatusEnum;
  redirectUrl: string;
  redirectFallbackUrl?: string;
  redirectMethod?: RedirectMethodEnum;
  redirectFallbackMethod?: RedirectFallbackMethodEnum;
  username?: string;
  password?: string;
  fallbackUsername?: string;
  fallbackPassword?: string;
}

export const callEngineModifyConferenceRequestSchema: Schema<CallEngineModifyConferenceRequest> = object(
  {
    status: ['status', optional(statusEnumSchema)],
    redirectUrl: ['redirectUrl', string()],
    redirectFallbackUrl: ['redirectFallbackUrl', optional(string())],
    redirectMethod: ['redirectMethod', optional(redirectMethodEnumSchema)],
    redirectFallbackMethod: [
      'redirectFallbackMethod',
      optional(redirectFallbackMethodEnumSchema),
    ],
    username: ['username', optional(string())],
    password: ['password', optional(string())],
    fallbackUsername: ['fallbackUsername', optional(string())],
    fallbackPassword: ['fallbackPassword', optional(string())],
  }
);
