/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  nullable,
  object,
  optional,
  Schema,
  string,
} from '../schema';

export interface ConferenceMemberState {
  callId?: string;
  conferenceId?: string;
  memberUrl?: string;
  mute?: boolean;
  hold?: boolean;
  callIdsToCoach?: string[] | null;
}

export const conferenceMemberStateSchema: Schema<ConferenceMemberState> = object(
  {
    callId: ['callId', optional(string())],
    conferenceId: ['conferenceId', optional(string())],
    memberUrl: ['memberUrl', optional(string())],
    mute: ['mute', optional(boolean())],
    hold: ['hold', optional(boolean())],
    callIdsToCoach: ['callIdsToCoach', optional(nullable(array(string())))],
  }
);
