/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ConferenceEventMethodEnum
 */
export enum ConferenceEventMethodEnum {
  POST = 'POST',
  GET = 'GET',
}

/**
 * Schema for ConferenceEventMethodEnum
 */
export const conferenceEventMethodEnumSchema: Schema<ConferenceEventMethodEnum> = stringEnum(ConferenceEventMethodEnum);
