/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for DisconnectMethodEnum
 */
export enum DisconnectMethodEnum {
  POST = 'POST',
  GET = 'GET',
}

/**
 * Schema for DisconnectMethodEnum
 */
export const disconnectMethodEnumSchema: Schema<DisconnectMethodEnum> = stringEnum(DisconnectMethodEnum);
