/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface Diversion {
  reason?: string;
  privacy?: string;
  unknown?: string;
  origTo?: string;
}

export const diversionSchema: Schema<Diversion> = object({
  reason: ['reason', optional(string())],
  privacy: ['privacy', optional(string())],
  unknown: ['unknown', optional(string())],
  origTo: ['origTo', optional(string())],
});
