/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for FallbackMethodEnum
 */
export enum FallbackMethodEnum {
  POST = 'POST',
  GET = 'GET',
}

/**
 * Schema for FallbackMethodEnum
 */
export const fallbackMethodEnumSchema: Schema<FallbackMethodEnum> = stringEnum(FallbackMethodEnum);
