/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for FileFormatEnum
 */
export enum FileFormatEnum {
  Mp3 = 'mp3',
  Wav = 'wav',
}

/**
 * Schema for FileFormatEnum
 */
export const fileFormatEnumSchema: Schema<FileFormatEnum> = stringEnum(FileFormatEnum);
