/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema } from '../schema';
import { State1Enum, state1EnumSchema } from './state1Enum';

export interface ModifyCallRecordingRequest {
  state: State1Enum;
}

export const modifyCallRecordingRequestSchema: Schema<ModifyCallRecordingRequest> = object(
  { state: ['state', state1EnumSchema] }
);
