/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, object, optional, Schema, string } from '../schema';
import {
  RedirectFallbackMethodEnum,
  redirectFallbackMethodEnumSchema,
} from './redirectFallbackMethodEnum';
import {
  RedirectMethodEnum,
  redirectMethodEnumSchema,
} from './redirectMethodEnum';
import { StateEnum, stateEnumSchema } from './stateEnum';

export interface ModifyCallRequest {
  state?: StateEnum | null;
  /** Required if state is 'active' */
  redirectUrl?: string | null;
  redirectFallbackUrl?: string | null;
  redirectMethod?: RedirectMethodEnum | null;
  redirectFallbackMethod?: RedirectFallbackMethodEnum | null;
  username?: string | null;
  password?: string | null;
  fallbackUsername?: string | null;
  fallbackPassword?: string | null;
  tag?: string | null;
}

export const modifyCallRequestSchema: Schema<ModifyCallRequest> = object({
  state: ['state', optional(nullable(stateEnumSchema))],
  redirectUrl: ['redirectUrl', optional(nullable(string()))],
  redirectFallbackUrl: ['redirectFallbackUrl', optional(nullable(string()))],
  redirectMethod: [
    'redirectMethod',
    optional(nullable(redirectMethodEnumSchema)),
  ],
  redirectFallbackMethod: [
    'redirectFallbackMethod',
    optional(nullable(redirectFallbackMethodEnumSchema)),
  ],
  username: ['username', optional(nullable(string()))],
  password: ['password', optional(nullable(string()))],
  fallbackUsername: ['fallbackUsername', optional(nullable(string()))],
  fallbackPassword: ['fallbackPassword', optional(nullable(string()))],
  tag: ['tag', optional(nullable(string()))],
});
