/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, object, optional, Schema, string } from '../schema';
import {
  RedirectFallbackMethodEnum,
  redirectFallbackMethodEnumSchema,
} from './redirectFallbackMethodEnum';
import {
  RedirectMethodEnum,
  redirectMethodEnumSchema,
} from './redirectMethodEnum';
import { StatusEnum, statusEnumSchema } from './statusEnum';

export interface ModifyConferenceRequest {
  status?: StatusEnum;
  redirectUrl?: string | null;
  redirectFallbackUrl?: string | null;
  redirectMethod?: RedirectMethodEnum | null;
  redirectFallbackMethod?: RedirectFallbackMethodEnum | null;
  username?: string | null;
  password?: string | null;
  fallbackUsername?: string | null;
  fallbackPassword?: string | null;
}

export const modifyConferenceRequestSchema: Schema<ModifyConferenceRequest> = object(
  {
    status: ['status', optional(statusEnumSchema)],
    redirectUrl: ['redirectUrl', optional(nullable(string()))],
    redirectFallbackUrl: ['redirectFallbackUrl', optional(nullable(string()))],
    redirectMethod: [
      'redirectMethod',
      optional(nullable(redirectMethodEnumSchema)),
    ],
    redirectFallbackMethod: [
      'redirectFallbackMethod',
      optional(nullable(redirectFallbackMethodEnumSchema)),
    ],
    username: ['username', optional(nullable(string()))],
    password: ['password', optional(nullable(string()))],
    fallbackUsername: ['fallbackUsername', optional(nullable(string()))],
    fallbackPassword: ['fallbackPassword', optional(nullable(string()))],
  }
);
