/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for State1Enum
 */
export enum State1Enum {
  Active = 'active',
  Completed = 'completed',
}

/**
 * Schema for State1Enum
 */
export const state1EnumSchema: Schema<State1Enum> = stringEnum(State1Enum);
