/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface Transcript {
  text?: string;
  confidence?: number;
}

export const transcriptSchema: Schema<Transcript> = object({
  text: ['text', optional(string())],
  confidence: ['confidence', optional(number())],
});
