/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, number, object, optional, Schema, string, boolean } from '../schema';
import {
  CallbackMethodEnum,
  callbackMethodEnumSchema,
} from './callbackMethodEnum';

export interface TranscribeRecordingRequest {
  callbackUrl?: string;
  callbackMethod?: CallbackMethodEnum | null;
  username?: string | null;
  password?: string | null;
  tag?: string | null;
  callbackTimeout?: number | null;
  detectLanguage?: boolean| undefined;
}

export const transcribeRecordingRequestSchema: Schema<TranscribeRecordingRequest> = object(
  {
    callbackUrl: ['callbackUrl', optional(string())],
    callbackMethod: [
      'callbackMethod',
      optional(nullable(callbackMethodEnumSchema)),
    ],
    username: ['username', optional(nullable(string()))],
    password: ['password', optional(nullable(string()))],
    tag: ['tag', optional(nullable(string()))],
    callbackTimeout: ['callbackTimeout', optional(nullable(number()))],
    detectLanguage: ['detectLanguage', optional(boolean())],
  }
);
