/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface Transcription {
  id?: string;
  url?: string;
  status?: string;
  completedTime?: string;
}

export const transcriptionSchema: Schema<Transcription> = object({
  id: ['id', optional(string())],
  url: ['url', optional(string())],
  status: ['status', optional(string())],
  completedTime: ['completedTime', optional(string())],
});
