/**
 * bandwidthLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface TranscriptionMetadata {
  id?: string;
  /** The current status of the transcription. Current values are 'none', 'processing', 'available', 'error', 'timeout', 'file-size-too-big', and 'file-size-too-small'. Additional states may be added in the future, so your application must be tolerant of unknown values. */
  status?: string;
  completedTime?: string;
  url?: string;
}

export const transcriptionMetadataSchema: Schema<TranscriptionMetadata> = object(
  {
    id: ['id', optional(string())],
    status: ['status', optional(string())],
    completedTime: ['completedTime', optional(string())],
    url: ['url', optional(string())],
  }
);
