name: Validate/Test SDK

on:
  pull_request:
    branches:
      - 'master'
      - 'main'

jobs:s
  build-and-test-sdk:
    name: Validate/Test SDK
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build and Test SDK
      run: |
           npm install
           npm run build
           npm run test --if-present